name: ELEVATE
favicon: null
layout_spectrum: 0.26045
typography_spectrum: 0.31065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4a890'
    - '#564d5c'
    - '#6a626b'
    - '#3c303c'
    - '#c8bd9f'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
